server:
  port: 9899
  servlet:
    context-path: /after-service
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: y%d*IWrh1KKfQD!E
      url: jdbc:mysql://172.26.20.230:3306/xiliulou_crm?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true


logging:
  config: classpath:logback-spring.xml
  level:
    com.xiliulou.afterservice: debug


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto

  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


xiliulou:
  urls:
    - /auth/**
    - /outer/**
    - /actuator/**
    - /error/**
jwt:
  secret: A0B1C2D3E4F5G6H7I8J9KALBMCNDOEPFQ0R1S2T3U4V5W6X7Y8Z8
  expire: 1296000

minio:
  endpoint: http://172.26.20.230
  port: 9000
  accessKey: by-xiliulou
  secretKey: by123456
  secure: false
  bucketName: test
