server:
  port: 9899
  servlet:
    context-path: /after-service
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: y%d*IWrh1KKfQD!E
      url: jdbc:mysql://192.168.0.236:3306/xiliulou_crm?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true

  servlet:
    multipart:
      # 文件最大限制
      max-file-size: 5MB
      # 请求最大限制
      max-request-size: 100MB
      enabled: true
      # 设置文件缓存的临界点,超过则先保存到临时目录,默认为0,所有文件都会进行缓存
      file-size-threshold: 0
  profiles:
    active: prod
logging:
  config: classpath:logback-spring-prod.xml
  level:
    com.xiliulou.afterserver.mapper: debug


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: true
    db-config:
      id-type: auto
      field-strategy: NOT_NULL
      logic-delete-value: 1
      logic-not-delete-value: 0


xiliulou:
  urls:
    - /auth/**
    - /outer/**
    - /actuator/**
    - /error/**
jwt:
  secret: A0B1C2D3E4F5G6H7I8J9KALBMCNDOEPFQ0R1S2T3U4V5W6X7Y8Z8
  expire: 1296000

minio:
  endpoint: http://192.168.0.236
  port: 9000
  accessKey: LUS0FLKBY835V0QLADFP
  secretKey: 9SyT5fhNSwaZCRv1MiKTc3JKLiEvTjxuIXDBB+XR
  secure: false
  bucketName: test
