server:
  port: 9899
  servlet:
    context-path: /after-service
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: y%d*IWrh1KKfQD!E
      url: jdbc:mysql://172.26.20.230:3306/xiliulou_crm?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
  redis:
    lettuce:
      pool:
        max-active: 1
        max-idle: 1
        min-idle: 1
    host:  ${REDIS-HOST:xiliulou-redis}
    database: 2

  klock:
    address: ${REDIS-HOST:xiliulou-redis}:6379
    wait-time: 20
    lease-time: 20
    database: 15

  servlet:
    multipart:
      # 文件最大限制
      max-file-size: 5MB
      # 请求最大限制
      max-request-size: 100MB
      enabled: true
      # 设置文件缓存的临界点,超过则先保存到临时目录,默认为0,所有文件都会进行缓存
      file-size-threshold: 0
  profiles:
    active: dev
logging:
  config: classpath:logback-spring-dev.xml
  level:
    com.xiliulou.afterserver.mapper: debug


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: true
    db-config:
      id-type: auto
      field-strategy: NOT_NULL
      logic-delete-value: 1
      logic-not-delete-value: 0


xiliulou:
  urls:
    - /auth/**
    - /outer/**
    - /actuator/**
    - /error/**

  token:
    infos:
      0:
        maxTokenCnt: 10
        expiryTimeMillis: 7200000
        maxExpiryTimeMillis: 7200000
      1:
        maxTokenCnt: 1
        expiryTimeMillis: 7200000
        maxExpiryTimeMillis: 7200000
      2:
        maxTokenCnt: 5
        expiryTimeMillis: 7200000
        maxExpiryTimeMillis: 7200000
      3:
        maxTokenCnt: 1
        expiryTimeMillis: 7776000000
        maxExpiryTimeMillis: 7776000000
      4:
        maxTokenCnt: 1
        expiryTimeMillis: 7776000000
        maxExpiryTimeMillis: 7776000000

jwt:
  #secret: A0B1C2D3E4F5G6H7I8J9KALBMCNDOEPFQ0R1S2T3U4V5W6X7Y8Z8
  secret: 20e5@cda38da811*27ed6fa.d226&8
  expire: 1296000

minio:
  endpoint: http://172.26.20.230
  #endpoint: http://172.26.20.231
  port: 9000
  accessKey: by-xiliulou
  secretKey: by123456
  secure: false
  bucketName: test

userrole:
  unShow: [1,2,3,4]
  userRole: [2]

storage:
  ossEndpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI5tC4goxYbeX99GMYaHY4
  accessKeySecret: XQ8zD6nrHoJIiy6iodn843ZUlB9xS5
  bucketName: xiliulou-strawberry
  #urlPrefix: wm-xiliulou-test
  #dir: after/
  ### oss:0 minio:1
  isUseOSS: 0
